<?php

namespace Main\MainBundle\Repository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends \Doctrine\ORM\EntityRepository
{
    public function mySlider()
    {
        $qb = $this->_em->createQueryBuilder('a');
        $qb ->select('a')
            ->from('MainBundle:Articles','a')
            ->leftJoin('MainBundle:Videos','v','WITH','a.id = v.id')

            ->addOrderBy('a.date_publication');
        return $qb->getQuery()->getResult();
    }

    public function findPrevious($id)
    {
        $qb = $this->createQueryBuilder('u');
        $qb ->select('u')
            ->where('u.id < :id')
            ->setParameter(':id',$id)
            ->orderBy('u.id','DESC')
            ->setFirstResult(0)
            ->setMaxResults(1);
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function findNext($id)
    {
        $qb = $this->createQueryBuilder('u');
        $qb ->select('u')
            ->where('u.id > :id')
            ->setParameter(':id',$id)
            ->orderBy('u.id','ASC')
            ->setFirstResult(0)
            ->setMaxResults(1);
        return $qb->getQuery()->getOneOrNullResult();
    }
//SELECT po.*, ph.* FROM MainBundle:Articles po
//LEFT JOIN MainBundle:Videos ph
//ORDER BY po.date DESC, ph.date DESC
}
