<?php

namespace Main\MainBundle\Repository;

/**
 * DonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindFirst()
    {
        $qb = $this->createQueryBuilder("tc");
        $qb->setMaxResults( 1 );
        $qb->orderBy("tc.id", "ASC");
        return $qb->getQuery()->getSingleResult();
    }
}
