<?php

namespace Main\MainBundle\Repository;

/**
 * EmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmissionRepository extends \Doctrine\ORM\EntityRepository
{
}
