<?php

namespace Main\MainBundle\Repository;

/**
 * PromotedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotedRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindDate()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb
            ->from('MainBundle:Promoted','d')
            ->addSelect('min(d.date)');

            return $qb->getQuery()
                ->getResult();
    }
}
